### PR TITLE
Examples update/cleanup

### PR DESCRIPTION
**Pull request by tejon**
- Relaxed upper bounds for linear, lens
- `Data.Foldable`/`Control.Applicative` `ifdef`'d in all examples
- All examples updated for new color handling
- All examples moved away from `[InitEverything]`
- Cured a constraint warning in `AudioExample.hs`
- Cleaned up imports in `OpenGLExample.hs`

### CODE REVIEW

**Comment by polarina** [comment]
OpenGL example doesn't compile for me after applying your patch:

    examples/OpenGLExample.hs:49:35: Not in scope: ‘<$>’

**Comment by tejon** [comment]
Whoops, I'm working on 7.10. Thought I got all the conditionals in, hope I didn't miss any more!

**Comment by polarina** [comment]
Great! It compiles now with just a warning.

    examples/OpenGLExample.hs:21:1: Warning:
        The import of ‘Data.Foldable’ is redundant
          except perhaps to import instances from ‘Data.Foldable’
        To import instances alone, use: import Data.Foldable()

**Comment by tejon** [comment]
Ha... `for_` isn't actually used anywhere in the file. Guess that line can just go. :)

I'm a little confused since Control.Applicative wasn't there before. So where was <$> coming from? Some deep re-export from the accidentally unqualified GL, or from Linear.Affine? Or was it just broken on <7.10 to begin with?

Anyway, everything's warning-free at my end now. Good for you too?

**Comment by polarina** [comment]
Looks good to me. Thanks!

**Comment by Velro** [comment]
I originally committed the OpenGL example. I never tested it on <7.10 before pushing it so it was probably broken on there to be begin with.
