### PR TITLE
Added -DSDL2_main_h to cpp-options

### LINKED ISSUE #139: GHC 8.0.2 on Windows "error: conflicting types for 'SDL_main'" workaround
`cpp-options: -D_SDL_main_h` needs to be added to the `.cabal` file to compile on Windows with GHC 8.0.2 (credits to \<RyanGlScott\> in #ghc http://ircbrowse.net/day/ghc/2017/01/28)

It looks like this is technically a problem with the hsc2hs implementation (see above irc discussion) so this isn't necessarily an issue with sdl2 itself, but if this cpp flag doesn't cause any other issues I can make a patch for it

### PR DESCRIPTION
**Pull request by schell**
This re-fixes #139 for windows.

### CODE REVIEW

**Comment by ocharles** [comment]
Thanks!

**Comment by Mikolaj** [comment]
The same trick helped for sdl2-ttf. Thank you!
